.eslintrc copy.yml, models/followship.js, models/like.js, models/reply.js, models/tweet.js, models/user.js
=> feat: revised model setting

controllers/user-controller.js, middleware/auth.js
=> User login authentication for admin&user

controllers/tweet-controller.js, controllers/user-controller.js, routes/modules/tweet.js
=> add getTweet function

app.js
=> fix: fix cors

controllers/tweet-controller.js, routes/modules/tweet.js
=> add postTweet function

controllers/tweet-controller.js, routes/modules/tweet.js, seeders/20230320153100-tweets-seed-file.js, seeders/20230321064700-replies-seed-file.js
已通過測試檔案，種子資料有更新，每篇推文都有隨機三位使用者留言！
等我我在修改一個地方
=> add get replies feature

controllers/tweet-controller.js, routes/modules/tweet.js
=> add post reply function

controllers/user-controller.js, models/reply.js, routes/modules/user.js
1. 修改回傳資料內容和新增錯誤提示，路由名稱改為 getUserReplies
2. 修改 reply model ，解決 id undefined 問題
3. 已成功跑過測試檔
4. API 文件已修改完成
=> revised get user replies function

controllers/user-controller.js, routes/index.js, routes/modules/followship.js, routes/modules/user.js
1. add followship module and route
2. add addFollowing function in user controller
3. pass requests: POST /api/followships test
Please review my code. Thank you😇
=> Add following

controllers/tweet-controller.js, models/like.js, routes/modules/tweet.js
1. 新增like/unlike feature
2. 修正 like model id undefined 問題
3. 已跑過測試檔案
4. API 文件已修改
=> Add like & unlike tweet

controllers/user-controller.js, routes/modules/followship.js
1. add removeFollowing route 
2. add removeFollowing function in user controller
3. pass request: DELETE /api/followships/:followingId test
=> feat: add removeFollowing function

controllers/tweet-controller.js
=> Fix: correct the error of missing await

controllers/followship-controller.js, routes/modules/followship.js
1. 新增 followship controller 處理 followship相關功能
2.更改 function 命名 : postFollowship & deleteFollowship
=> Chore: implement followship controller for followship feature & rename function

routes/index.js, routes/modules/user.js
=> feat: change the login route to api/signin

controllers/user-controller.js, routes/modules/user.js
1. 新增功能：取得某使用者發過的推文 
2.已通過測試檔案
3.已新增此API文件
額外修正 getUserReplies : 判斷當前使用者的 id 是否與請求中的 userId 相符
=> Add get user tweets function

controllers/admin-controller.js, routes/index.js, routes/modules/admin.js
1. 新增管理者看見站內所有的使用者功能
2. 已成功跑過測試檔
=> Add admin getUsers function

controllers/admin-controller.js, routes/modules/admin.js
=> feat: add admin deleteTweet function

controllers/admin-controller.js, routes/modules/admin.js
=> Add admin getTweets

controllers/user-controller.js, routes/modules/user.js, test/requests/user.spec.js
1. add getUserFollowings route in user module
2. add getUserFollowings function in user controller
3. pass test
=> Add getUserFollowings

controllers/user-controller.js, routes/modules/user.js, test/requests/user.spec.js
1. Add get user followers route in user module
2. Add get user followers function in user controller
3. pass test
=> Add get user followers function

controllers/tweet-controller.js, controllers/user-controller.js
=> fix: revise return data content

config/passport.js, routes/index.js, routes/modules/admin.js, routes/modules/user.js
=> feat: implement role-based login page access restriction

README.md, controllers/user-controller.js
=> fix: fix signUp feature to comply with test file

controllers/user-controller.js, routes/modules/user.js
=> feat: add editUserAccount function

controllers/user-controller.js, migrations/20230328172101-add-avatar-and-cover-defaultValue.js, routes/modules/user.js
Give default value to cover and avatar in users table
=> Add cover and avatar default value

controllers/admin-controller.js, controllers/followship-controller.js, controllers/tweet-controller.js, controllers/user-controller.js
1. 修改status code號碼
2. 移除不必要的錯誤條件 error msg
3. 修改admin getTweets description 快覽50字
=> Fix: error message and status code number

controllers/admin-controller.js, controllers/user-controller.js
1. update data format in getTopUsers function
2. update API doc
=> feat: update return data format in getTopUsers function

controllers/user-controller.js
1. fix isFollowing logic in getUser function
2.  add default value to cover and avatar in getUser
=> feat: fix isFollowing and add default value to cover/avatar

controllers/followship-controller.js, controllers/user-controller.js
getTopUsers:
1. fix: only role 'users' are allowed to be top users
2. fix: current user should not appear on top users list
addFollowings:
1. fix: only role 'users' can be followed
deleteFollowings:
1. fix: users can only remove followship from role 'users'
=> Fix bugs in getTopUsers / addFollowings /deleteFollowings

controllers/user-controller.js
1. fix: add error message when role 'user' try to get into role 'admin' page
=> fix: fix role authorization error

controllers/user-controller.js
fix role authorization error in getFollowing/getFollowers
=> fix: fix role authorization error in getFollowing/getFollowers

controllers/user-controller.js
rename return data in getUserFollowers/getUserFollowings
=> fix: rename return data in getUserFollowers/getUserFollowings

controllers/admin-controller.js
=> fix: remove admin in users list

controllers/user-controller.js, helpers/file-helpers.js
update getUsersFollowing/Followers when followcount is zero
=> fix: update getUsersFollowing/Followers when followcount is zero

controllers/admin-controller.js
deleting the selected range to pass the test file
=> fix: deleting the selected range to pass the test file

controllers/admin-controller.js
修正管理者刪除使用者貼文時，應將相關回覆及喜歡的紀錄一併刪除
=> fix: related replies and likes should be deleted when the Tweet is deleted

helpers/file-helpers.js
=> feat: set the file format and size for uploading images

controllers/user-controller.js
=> feat: catch error message for image format and size mismatch

README.md
=> feat: modify cover photo

seeders/20230320152709-users-seed-file.js
=> fix: update images in seeders

helpers/file-helpers.js
modify image upload failed msg in Chinese
=> feat: modify image upload failed msg
